// components/countries.ts
// [UPDATED] 英語名(enName)のアルファベット順にソート

export interface Country {
    code: string;
    name: string;
    enName: string;
}

export const countries: Country[] = [
    { code: 'AR', name: 'アルゼンチン', enName: 'Argentina' },
    { code: 'AU', name: 'オーストラリア', enName: 'Australia' },
    { code: 'AT', name: 'オーストリア', enName: 'Austria' },
    { code: 'BH', name: 'バーレーン', enName: 'Bahrain' },
    { code: 'BE', name: 'ベルギー', enName: 'Belgium' },
    { code: 'BR', name: 'ブラジル', enName: 'Brazil' },
    { code: 'BN', name: 'ブルネイ', enName: 'Brunei' },
    { code: 'BG', name: 'ブルガリア', enName: 'Bulgaria' },
    { code: 'KH', name: 'カンボジア', enName: 'Cambodia' },
    { code: 'CA', name: 'カナダ', enName: 'Canada' },
    { code: 'CL', name: 'チリ', enName: 'Chile' },
    { code: 'CN', name: '中国', enName: 'China' },
    { code: 'CO', name: 'コロンビア', enName: 'Colombia' },
    { code: 'HR', name: 'クロアチア', enName: 'Croatia' },
    { code: 'CZ', name: 'チェコ', enName: 'Czech Republic' },
    { code: 'DK', name: 'デンマーク', enName: 'Denmark' },
    { code: 'EG', name: 'エジプト', enName: 'Egypt' },
    { code: 'EE', name: 'エストニア', enName: 'Estonia' },
    { code: 'FI', name: 'フィンランド', enName: 'Finland' },
    { code: 'FR', name: 'フランス', enName: 'France' },
    { code: 'DE', name: 'ドイツ', enName: 'Germany' },
    { code: 'GR', name: 'ギリシャ', enName: 'Greece' },
    { code: 'HK', name: '香港', enName: 'Hong Kong' },
    { code: 'HU', name: 'ハンガリー', enName: 'Hungary' },
    { code: 'IN', name: 'インド', enName: 'India' },
    { code: 'ID', name: 'インドネシア', enName: 'Indonesia' },
    { code: 'IE', name: 'アイルランド', enName: 'Ireland' },
    { code: 'IL', name: 'イスラエル', enName: 'Israel' },
    { code: 'IT', name: 'イタリア', enName: 'Italy' },
    { code: 'JP', name: '日本', enName: 'Japan' },
    { code: 'KE', name: 'ケニア', enName: 'Kenya' },
    { code: 'KW', name: 'クウェート', enName: 'Kuwait' },
    { code: 'LA', name: 'ラオス', enName: 'Laos' },
    { code: 'LV', name: 'ラトビア', enName: 'Latvia' },
    { code: 'LT', name: 'リトアニア', enName: 'Lithuania' },
    { code: 'LU', name: 'ルクセンブルク', enName: 'Luxembourg' },
    { code: 'MO', name: 'マカオ', enName: 'Macau' },
    { code: 'MY', name: 'マレーシア', enName: 'Malaysia' },
    { code: 'MX', name: 'メキシコ', enName: 'Mexico' },
    { code: 'MA', name: 'モロッコ', enName: 'Morocco' },
    { code: 'NL', name: 'オランダ', enName: 'Netherlands' },
    { code: 'NZ', name: 'ニュージーランド', enName: 'New Zealand' },
    { code: 'NG', name: 'ナイジェリア', enName: 'Nigeria' },
    { code: 'NO', name: 'ノルウェー', enName: 'Norway' },
    { code: 'OM', name: 'オマーン', enName: 'Oman' },
    { code: 'PE', name: 'ペルー', enName: 'Peru' },
    { code: 'PH', name: 'フィリピン', enName: 'Philippines' },
    { code: 'PL', name: 'ポーランド', enName: 'Poland' },
    { code: 'PT', name: 'ポルトガル', enName: 'Portugal' },
    { code: 'QA', name: 'カタール', enName: 'Qatar' },
    { code: 'RO', name: 'ルーマニア', enName: 'Romania' },
    { code: 'SA', name: 'サウジアラビア', enName: 'Saudi Arabia' },
    { code: 'SG', name: 'シンガポール', enName: 'Singapore' },
    { code: 'SK', name: 'スロバキア', enName: 'Slovakia' },
    { code: 'SI', name: 'スロベニア', enName: 'Slovenia' },
    { code: 'ZA', name: '南アフリカ', enName: 'South Africa' },
    { code: 'KR', name: '韓国', enName: 'South Korea' },
    { code: 'ES', name: 'スペイン', enName: 'Spain' },
    { code: 'SE', name: 'スウェーデン', enName: 'Sweden' },
    { code: 'CH', name: 'スイス', enName: 'Switzerland' },
    { code: 'TW', name: '台湾', enName: 'Taiwan' },
    { code: 'TH', name: 'タイ', enName: 'Thailand' },
    { code: 'TR', name: 'トルコ', enName: 'Turkey' },
    { code: 'AE', name: 'アラブ首長国連邦', enName: 'UAE' },
    { code: 'GB', name: 'イギリス', enName: 'United Kingdom' },
    { code: 'US', name: 'アメリカ', enName: 'United States' },
    { code: 'VN', name: 'ベトナム', enName: 'Vietnam' }
];